version: "3.8"
networks:
  internal_C:
    driver: macvlan
    driver_opts:
      parent: ens19.2
    name: internal_C
    ipam:
      config:
        - subnet: "10.1.2.0/24"
          gateway: "10.1.2.254"
  dmz_C:
    driver: macvlan
    driver_opts:
      parent: ens19.1
    name: dmz_C
    ipam:
      config:
        - subnet: "172.1.1.0/24"
          gateway: "172.1.1.254"
  pubnet:
    name: pubnet
    ipam:
      config:
        - subnet: "172.31.255.0/24"
          gateway: "172.31.255.254"
  internet:
    driver: macvlan
    driver_opts:
      parent: ens20
    name: internet
    ipam:
      config:
        - subnet: "172.31.50.0/24"
          gateway: "172.31.50.254"

services:
  # DMZ
  er_c: # Connects to dmz and pubnet
    build: ./edge_router
    container_name: er_c
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    entrypoint: er_c_entrypoint
    networks:
      dmz_C:
        ipv4_address: er_c_dmz_c
      pubnet:
        ipv4_address: er_c_pubnet
      internet:
        ipv4_address: er_c_internet
  r_c: # Also connects to internal
    build: ./router
    container_name: r_c
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    networks:
      internal_C:
        ipv4_address: r_c_internal_c
      dmz_C:
        ipv4_address: r_c_dmz_c
    command: [ r_c_default_route ] # This or er_c_dmz_c? O q é melhor¿
  dns:
    build: ./dns
    container_name: dns
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/docker/compose/porto/dns/db.myorg.net:/etc/bind/db.myorg.net
      - /etc/docker/compose/porto/dns/named.conf.local:/etc/bind/named.conf.local
      - /etc/docker/compose/porto/dns/named.conf.options:/etc/bind/named.conf.options
    entrypoint: dns_entrypoint
    networks:
      dmz_C:
        ipv4_address: dns_dmz_c
  # Internal
  netmanager1:
    build: ./netubuntu
    container_name: netmanager1
    cap_add:
      - NET_ADMIN
    entrypoint: netmanager1_entrypoint
    networks:
      internal_C:
        ipv4_address: netmanager1_internal_c
  dhcp_c:
    build: ./dhcp
    container_name: dhcp_c
    cap_add:
      - NET_ADMIN
    entrypoint: dhcp_c_entrypoint
    networks:
      internal_C:
        ipv4_address: dhcp_c_internal_c
